image: microsoft/dotnet:latest

build:
  stage: build
  before_script:
    - cd SubterfugeCore
    - dotnet restore
  script:
    - dotnet build
test:
    stage: test
    script:
        - cd ..
        - cd SubterfugeCoreTest
        - dotnet test
pages:
  script:
    - cd ..
    - cd SubterfugeCore
    - choco install docfx
    - docfx docfx.json
    - mv _site public
  artifacts:
    paths:
      - public