build:
  stage: build
  script:
    - C:\Tools\nuget.exe restore
    - cmd.exe /C " "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" /p:Configuration=Release /t:Clean;Build SubterfugeRemake.Shared.sln " && exit %%ERRORLEVEL%%
pages:
  image: erothejoker/docker-docfx:latest
  script:
    - docfx SubterfugeCore/docfx.json
    - mv SubterfugeCore/_site public
  artifacts:
    paths:
      - public